package RefactoreSamples;

/**
 * Created by aganezov on 10/22/15.
 * JetBrains GWU
 */

/* Class created via    Ctrl + T -> Push Members Down... in BaseClass*/
public class BaseClassSubclass extends BaseClass {
    /* Parameter extracted by Ctrl + T -> Extract Parameter */
    public void greet(String greeting){
        /* Variable extracted by Ctrl + T -> Extract Variable */
        StringBuilder stringBuilder = new StringBuilder();
        /* Variable extracted by Ctrl + T -> Extract Variable */

        /* Method invocation generated by Ctrl + T -> Extract Method */
        /* Parameter added by Ctrl + T (in appendName method) -> Extract parameter */
        appendName(stringBuilder, "My name");
        System.out.println(greeting);
    }

    /* Generated by Ctrl + T -> Extract Method */
    /* Parameter extracted by Ctrl + T -> Extract parameter */
    private void appendName(StringBuilder stringBuilder, String name) {
        /* Variable was inlined by    Ctrl + T -> Inline Variable */
        stringBuilder.append(name.toLowerCase());
    }
}
