import gwu.jetbrains.debugging.BubbleSort;
import gwu.jetbrains.debugging.JBGWUException;
import gwu.jetbrains.debugging.QuickSort;

import java.util.Arrays;
import java.util.Random;


public class Main {

    public static final int SIZE = 100000;
    public static final Random GENERATOR = new Random();

    /* Generated by         psvm + Tab      */
    public static void main(String[] args) throws InterruptedException, JBGWUException {
        final int[] array = new int[SIZE];
        for (int i = 0; i < SIZE; i++) {
            array[i] = GENERATOR.nextInt();
        }
        final Thread quickSortThread = new Thread(() -> {
            QuickSort.sort(Arrays.copyOf(array, array.length));
        }, "Quick sort");

        final Thread bubbleThread = new Thread(() -> {
            BubbleSort.sort(Arrays.copyOf(array, array.length));
        }, "Bubble sort");

        quickSortThread.start();
        bubbleThread.start();

        quickSortThread.join();
        bubbleThread.join();
    }
}
