/**
 * Created by aganezov on 10/7/15.
 * JetBrains GWU
 */
public class Main {

    /* Generated by         psvm + Tab      */
    public static void main(String[] args) {

        /* Generate by      iter + Tab      */
        for (String arg : args) {

        }
    }
}
