import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;

/**
 * Created by aganezov on 10/7/15.
 * JetBrains GWU
 */
public class Main {

    /* Generated by         psvm + Tab      */
    public static void main(String[] args) throws FileNotFoundException {

        /* Generate by      iter + Tab      */
        for (String arg : args) {

            /* Generated by     sout + Tab      */
            System.out.println("Hello JetBrains GWU");

            /* File path is created by injecting File reference into a string
                        Alt + Enter --> Inject language or reference
               And by using basic completion        Cmd + Space
            */
            BufferedReader reader = new BufferedReader(new FileReader("GenerateSamples/Dummy.java"));
        }
    }
}
